//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://www.w3.org/2003/05/soap-envelope", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED, xmlns = {
    @jakarta.xml.bind.annotation.XmlNs(prefix = "env", namespaceURI = "http://www.w3.org/2003/05/soap-envelope")
})
package io.github.rawvoid.soap.model.v1_2;
