//
// This file was generated by the Eclipse Implementation of JAXB, v4.0.6 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
//


package io.github.rawvoid.soap.model.v1_2;

import jakarta.annotation.Generated;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.XmlValue;
import lombok.Data;
import lombok.experimental.Accessors;


/**
 * &lt;p&gt;Java class for reasontext complex type&lt;/p&gt;.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.&lt;/p&gt;
 * 
 * &lt;pre&gt;{&#064;code
 * &lt;complexType name="reasontext"&gt;
 *   &lt;simpleContent&gt;
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;string"&gt;
 *       &lt;attribute ref="{http://www.w3.org/XML/1998/namespace}lang use="required""/&gt;
 *     &lt;/extension&gt;
 *   &lt;/simpleContent&gt;
 * &lt;/complexType&gt;
 * }&lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "reasontext", propOrder = {
    "value"
})
@Data
@Accessors(chain = true)
@Generated({
    "https://github.com/rawvoid/jaxb-plugins"
})
public class ReasonText {

    @XmlValue
    protected String value;
    /**
     * &lt;pre&gt;
     * &amp;lt;?xml version="1.0" encoding="UTF-8"?&amp;gt;&amp;lt;div xmlns="http://www.w3.org/1999/xhtml" xmlns:xs="http://www.w3.org/2001/XMLSchema"&amp;gt;
     *      
     *       &amp;lt;h3&amp;gt;lang (as an attribute name)&amp;lt;/h3&amp;gt;
     *       &amp;lt;p&amp;gt;
     *        denotes an attribute whose value
     *        is a language code for the natural language of the content of
     *        any element; its value is inherited.  This name is reserved
     *        by virtue of its definition in the XML specification.&amp;lt;/p&amp;gt;
     *      
     *     &amp;lt;/div&amp;gt;
     * &lt;/pre&gt;
     * 
     *     
     * &lt;pre&gt;
     * &amp;lt;?xml version="1.0" encoding="UTF-8"?&amp;gt;&amp;lt;div xmlns="http://www.w3.org/1999/xhtml" xmlns:xs="http://www.w3.org/2001/XMLSchema"&amp;gt;
     *      &amp;lt;h4&amp;gt;Notes&amp;lt;/h4&amp;gt;
     *      &amp;lt;p&amp;gt;
     *       Attempting to install the relevant ISO 2- and 3-letter
     *       codes as the enumerated possible values is probably never
     *       going to be a realistic possibility.  
     *      &amp;lt;/p&amp;gt;
     *      &amp;lt;p&amp;gt;
     *       See BCP 47 at &amp;lt;a href="http://www.rfc-editor.org/rfc/bcp/bcp47.txt"&amp;gt;
     *        http://www.rfc-editor.org/rfc/bcp/bcp47.txt&amp;lt;/a&amp;gt;
     *       and the IANA language subtag registry at
     *       &amp;lt;a href="http://www.iana.org/assignments/language-subtag-registry"&amp;gt;
     *        http://www.iana.org/assignments/language-subtag-registry&amp;lt;/a&amp;gt;
     *       for further information.
     *      &amp;lt;/p&amp;gt;
     *      &amp;lt;p&amp;gt;
     *       The union allows for the 'un-declaration' of xml:lang with
     *       the empty string.
     *      &amp;lt;/p&amp;gt;
     *     &amp;lt;/div&amp;gt;
     * &lt;/pre&gt;
     * 
     */
    @XmlAttribute(name = "lang", namespace = "http://www.w3.org/XML/1998/namespace", required = true)
    protected String lang;

}
